[project]
name = "hackathon-hangman"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "faker>=37.3.0",
    "rich>=14.0.0",
    "wikipedia>=1.4.0",
]
